version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: daily
    groups:
      patterns: "*"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    groups:
      patterns: "*"

  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
