version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: daily
    groups:
      groupall:
        patterns: "*"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    groups:
      groupall:
        patterns: "*"

  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: daily
