apiVersion: nais.io/v1
kind: Naisjob
metadata:
  labels:
    team: k9saksbehandling
  name: sif-github-stats-job
  namespace: k9saksbehandling
spec:
  image: "{{ image }}"
  schedule: "0 5-19 * * *"
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  backoffLimit: 1
  envFrom:
    - secret: sif-stats-github-pat
  env:
    - name: PUSH_GATEWAY_ADDRESS
      value: "prometheus-pushgateway.nais-system:9091"
    - name: GITHUB_API_VERSION
      value: "2022-11-28"
    - name: GITHUB_API_URL
      value: "https://api.github.com/"
  accessPolicy:
    outbound:
      rules:
        - application: prometheus-pushgateway
          namespace: nais-system
      external:
        - host: "api.github.com"
