apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    team: k9saksbehandling
  name: sif-influx-export
  namespace: k9saksbehandling
spec:
  image: {{image}}
  port: 8080
  ttl: 3h
  replicas:
    max: 1
    min: 1
  resources:
    requests:
      cpu: 200m
      memory: 128Mi