name: Dependabot security alerts
on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 1'
jobs:
  dependabot-alerts:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 18
          cache: 'npm'

      - run: npm ci

      - run: gh search repos archived:false --topic=sykdom-i-familien --owner=navikt --limit=200 --json "name" --jq ".[] | .name" > repos.txt
        env:
          GITHUB_TOKEN: ${{ secrets.READER_TOKEN }}

      - run: npm run dependabot-alerts
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_PAT }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
